import fs from 'fs';
import path from 'path';
import os from 'os';
import { Worker, Queue, Job } from 'bullmq';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import { redis } from '../lib/db/redis';
import { Report } from '../lib/models/Report';

export const REPORT_QUEUE = 'report-gen';
export const reportQueue = new Queue(REPORT_QUEUE, {
  connection: redis,
  defaultJobOptions: {
    attempts: 2,
    backoff: { type: 'fixed', delay: 3000 },
    removeOnComplete: 100,
    removeOnFail: 500,
  },
});

/**
 * Builds clean HTML template for PDF institutional report generation.
 */
function buildReportHtml(reportData: Record<string, unknown>): string {
  const title = (reportData.title as string) || 'Arthora - Investment Research Report';
  const reportType = (reportData.type as string) || 'Portfolio Analysis';
  const generatedAt = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      padding: 32px;
      color: #1A1B2E;
      background: #FFFFFF;
      font-size: 13px;
      line-height: 1.6;
    }
    .header {
      border-bottom: 2px solid #6C63FF;
      padding-bottom: 16px;
      margin-bottom: 24px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .logo {
      font-size: 22px;
      font-weight: 800;
      color: #0D0E1A;
    }
    .logo span {
      color: #00D2FF;
    }
    .report-meta {
      text-align: right;
      font-size: 11px;
      color: #666;
    }
    h1 {
      font-size: 18px;
      margin: 0 0 8px 0;
      color: #0D0E1A;
    }
    .badge {
      display: inline-block;
      padding: 4px 8px;
      background: #EAE8FF;
      color: #6C63FF;
      border-radius: 6px;
      font-size: 11px;
      font-weight: 600;
      margin-bottom: 16px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 16px;
      margin-bottom: 24px;
    }
    th, td {
      border: 1px solid #E2E8F0;
      padding: 10px 12px;
      text-align: left;
    }
    th {
      background: #F8FAFC;
      font-weight: 600;
      color: #334155;
    }
    .footer {
      border-top: 1px solid #E2E8F0;
      padding-top: 12px;
      font-size: 10px;
      color: #94A3B8;
      text-align: center;
      margin-top: 40px;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo">Arthora <span>India</span></div>
      <div style="font-size: 10px; color: #64748B; text-transform: uppercase;">Institutional Investment Research</div>
    </div>
    <div class="report-meta">
      <div>Report Date: <strong>${generatedAt}</strong></div>
      <div>Type: <strong>${reportType}</strong></div>
    </div>
  </div>

  <h1>${title}</h1>
  <div class="badge">${reportType.toUpperCase()}</div>

  <p>This report compiles quantitative metrics, risk-adjusted returns, and asset distribution generated by Arthora's automated research engines.</p>

  <table>
    <thead>
      <tr>
        <th>Asset / Metric</th>
        <th>Category / Detail</th>
        <th>Benchmark / Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Target Investment Horizon</td>
        <td>Quantitative Modeling</td>
        <td>Long Term (5+ Years)</td>
      </tr>
      <tr>
        <td>Benchmark Comparison</td>
        <td>NIFTY 50 TRI Index</td>
        <td>Historical Alpha Tracked</td>
      </tr>
      <tr>
        <td>Calculation Model</td>
        <td>Modern Portfolio Theory + Monte Carlo</td>
        <td>10,000 Iterations</td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    Disclaimer: This document is for research and educational purposes only and does not constitute SEBI registered financial advice. Mutual fund investments are subject to market risks.
  </div>
</body>
</html>
  `;
}

/**
 * BullMQ Worker generating PDF analysis reports via Chromium & Puppeteer.
 */
export function createReportWorker(): Worker {
  const worker = new Worker(
    REPORT_QUEUE,
    async (job: Job) => {
      const { reportId } = job.data as { reportId: string };
      console.log(
        JSON.stringify({
          timestamp: new Date().toISOString(),
          worker: 'reportGen',
          event: 'job_started',
          jobId: job.id,
          reportId,
        }),
      );

      const reportDoc = await Report.findById(reportId);
      if (!reportDoc) {
        throw new Error(`Report document ${reportId} not found`);
      }

      reportDoc.status = 'processing';
      await reportDoc.save();

      try {
        // Configure Chromium executable path
        const isWindows = process.platform === 'win32';
        let executablePath: string;

        if (isWindows) {
          // Standard Windows Chrome paths fallback
          const winChrome = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
          const winChromeX86 = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe';
          if (fs.existsSync(winChrome)) {
            executablePath = winChrome;
          } else if (fs.existsSync(winChromeX86)) {
            executablePath = winChromeX86;
          } else {
            executablePath = await chromium.executablePath();
          }
        } else {
          executablePath = await chromium.executablePath();
        }

        const browser = await puppeteer.launch({
          args: chromium.args,
          defaultViewport: ((chromium as unknown as Record<string, unknown>).defaultViewport as { width: number; height: number }) || { width: 1920, height: 1080 },
          executablePath,
          headless: true,
        });

        const page = await browser.newPage();
        const htmlContent = buildReportHtml(reportDoc.toObject() as unknown as Record<string, unknown>);
        await page.setContent(htmlContent, { waitUntil: 'domcontentloaded' });

        const pdfBuffer = await page.pdf({
          format: 'A4',
          printBackground: true,
          margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
        });

        await browser.close();

        // Save PDF to reports directory
        const reportsDir = path.join(os.tmpdir(), 'arthora-reports');
        if (!fs.existsSync(reportsDir)) {
          fs.mkdirSync(reportsDir, { recursive: true });
        }

        const filePath = path.join(reportsDir, `${reportId}.pdf`);
        fs.writeFileSync(filePath, Buffer.from(pdfBuffer));

        reportDoc.status = 'completed';
        reportDoc.downloadUrl = `/api/v1/reports/${reportId}/download`;
        reportDoc.expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days retention
        await reportDoc.save();

        return { reportId, status: 'completed', fileSize: pdfBuffer.length };
      } catch (err) {
        reportDoc.status = 'failed';
        await reportDoc.save();
        throw err;
      }
    },
    {
      connection: redis,
      concurrency: 2,
    },
  );

  return worker;
}
